name: Bug Report
description: Report a bug
title: 'short issue description'
labels: [bug]
body:
  - type: textarea
    id: problem
    attributes:
      label: What is the problem?
      description: |
        * What did you expect to happen?
        * What actually happened?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: Minimal amount of code that causes the bug (if possible) or a reference.
    validations:
      required: true

  - type: checkboxes
    id: sign-in-method
    attributes:
      label: Sign in Method
      description: How did you sign in to AWS? (Select all that apply)
      options:
        - label: 'Direct login to target account via AWS SSO'
        - label: 'Direct login to target account via IAM user'
        - label: 'Login to a jump account via AWS SSO, then switch role to target account'
        - label: 'Login to a jump account via IAM user, then switch role to target account'
        - label: 'Sign in as the root user'

  - type: input
    id: browser
    attributes:
      label: Browser Name
    validations:
      required: true

  - type: input
    id: browser-version
    attributes:
      label: Browser Version
    validations:
      required: true

  - type: textarea
    id: other
    attributes:
      label: Other information
      description: |
        e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, slack, etc
    validations:
      required: false
