name: Feature Request
description: Request a new feature
title: "short issue description"
labels: [feature-request, needs-triage]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Short description of the feature you are proposing.
    validations:
      required: true

  - type: textarea
    id: other
    attributes:
      label: Other information
      description: |
        e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, slack, etc
    validations:
      required: false

  - type: checkboxes
    id: acknowledgments
    attributes:
      label: Acknowledge
      options:
        - label: I may be able to implement this feature request
          required: false
        - label: This feature might incur a breaking change
          required: false

  - type: markdown
    attributes:
      value: |
        ---

        This is a :rocket: Feature Request